
on: [push]
  
push:
    branches:
    - src-pages

jobs:
  jekyll_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch for building Pages
        uses: actions/checkout@v1
        with:
          ref: src-pages
          fetch-depth: 10

      - name: Make build destination directory
        run: mkdir -vp ~/www/repository-name

      - name: Jekyll Build
        uses: gha-utilities/jekyll-build@v0.1.1
        with:
          source: ./
          destination: ~/www/repository-name

      - name: Upload Built Pages
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Complied-Jekyll-Pages
          path: ~/www/repository-name
